version:                "3"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - C:/Users/aditi/OneDrive/Desktop/ML_Docker:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container